ServerApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]

admin.site.site_header = "Admin"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to ServerApp Admin Portal"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calendarapp/urls.py
from django.urls import path
from . import views

app_name = 'calendarapp'
urlpatterns = [
    path('', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/(?P<event_id>\d+)/', views.event, name='event_edit'),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('todo/', views.todoappView, name='todo'),
    path('update_task/<str:new_name>/', views.updateTask, name='update_task'),
    path('delete_task/<int:id>/', views.deleteTask, name='delete_task'),
]

calendarapp/models.py
from django.db import models
from django.urls import reverse

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    
    @property
    def get_html_url(self):
        url = reverse('calendarapp:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

calendarapp/forms.py
from django.forms import ModelForm, DateInput
from calendarapp.models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

calendarapp/views.py
from datetime import datetime, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe

from .models import *
from .utils import Calendar
from .forms import EventForm

class CalendarView(generic.ListView):
    model = Event
    template_name = 'calendarapp/calendar.html'
    
    #overrides existing function to calculate prev_month, next_month and form the calendar
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # use today's date for generating the calendar
        d = self.get_date(self.request.GET.get('month', None))
        # Instantiate calendar class with today's year and date
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = Calendar.prev_month(cal, d)
        context['next_month'] = Calendar.next_month(cal, d)
        return context

    def get_date(self, req_day):
        if req_day:
            year, month = (int(x) for x in req_day.split('-'))
            return date(year, month, day=1)
        return datetime.today()

#add events to the calendar
def event(request, event_id=None):
    instance = Event()
    if event_id:
        #View or edit existing event    
        instance = get_object_or_404(Event, pk=event_id)
    else:
        #Create a new event 
        instance = Event()
    
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('calendarapp:calendar'))
    return render(request, 'calendarapp/event.html', {'form': form})

templates/calendarapp/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
      crossorigin="anonymous">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
    <link rel="stylesheet" type="text/css" href="{% static 'calendarapp/css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <title>Calendar</title>
</head>
<body>
  <div class="sidebar">
		<a href="{% url 'employdata' %}"><i class="fa fa-home" style="font-size: 40px;"></i><p style="font-size: small;">Home</p></a>
		<a href="{% url 'workhome' %}"><i class="fa fa-users" style="font-size: 40px;"></i><p style="font-size: small;">Workspace</p></a>
		<a href="{% url 'inbox' %}"><i class="fa fa-envelope" style="font-size: 40px;"></i><p style="font-size: small;">Mail</p></a>
		<a class="active" href="{% url 'calendarapp:calendar' %}"><i class="fa fa-calendar" style="font-size: 40px;"></i><p style="font-size: small;">Calendar</p></a>
		<a href="{% url 'todo:todo' %}"><i class="fas fa-tasks" style="font-size: 40px;"></i><p style="font-size: small;">To-do</p></a>
		<a href="{% url 'chat' request.user %}"><i class="fas fa-comment-dots" style="font-size: 40px;"></i><p style="font-size: small;">Chat</p></a>
		<a href="{% url 'logout' %}"><i class="fa fa-sign-out" style="font-size: 40px;"></i><p style="font-size: small;">Logout</p></a>
	</div>
    <h1 class="title">{% block title %}{% endblock %}</h1>
    <hr>
  
    {% block content %}
    {% endblock %}

    {% block script %}
    {% endblock %}
</body>
</html>

templates/calendarapp/calendar.html
{% extends 'calendarapp/base.html' %}

{% block title %}
Calendar
{% endblock %}

{% block content %}
<div class="content">
	<a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'calendarapp:calendar' %}?{{ next_month }}"> Next Month </a>
    <a class="btn btn-info right" href="{% url 'calendarapp:event_new' %}"> New Event </a>
	{{ calendar }}
</div>
{% endblock %}

templates/calendarapp/event.html
{% extends 'calendarapp/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}