ServerApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]

admin.site.site_header = "Admin"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to ServerApp Admin Portal"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calendarapp/urls.py
from django.urls import path
from . import views

app_name = 'calendarapp'
urlpatterns = [
    path('', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/(?P<event_id>\d+)/', views.event, name='event_edit'),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('todo/', views.todoappView, name='todo'),
    path('update_task/<str:new_name>/', views.updateTask, name='update_task'),
    path('delete_task/<int:id>/', views.deleteTask, name='delete_task'),
]

todo/models.py
from django.db import models

class Task(models.Model):
    title = models.CharField(max_length = 100)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title

todo/forms.py
from django import forms
from django.forms import ModelForm

from .models import *

class TaskForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Add new task'}))

    class Meta:
        model = Task
        fields = '__all__'

todo/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from .models import *
from .forms import *

def todoappView(request):
    all_items = Task.objects.all()

    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/todo/')
    
    context = {'all_items': all_items, 'form': form}
    return render(request, 'todo/list.html', context)

def updateTask(request, new_name):
    task = Task.objects.get(id=new_name)
    form = TaskForm(instance=task)
    task.delete()  #deleting old instance of the task

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
        return redirect('/todo/')
    
    context = {'form': form}
    return render(request, 'todo/update_task.html', context)

def deleteTask(request, id):
    item = Task.objects.get(id=id)
    item.delete()
    return redirect('/todo/')

templates/todo/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
  <link rel="stylesheet" type="text/css" href="{% static 'todo/css/styles.css' %}">
  <title>To-do</title>
</head>
<body>
  <div class="sidebar">
		<a href="{% url 'employdata' %}"><i class="fa fa-home" style="font-size: 40px;"></i><p style="font-size: small;">Home</p></a>
		<a href="{% url 'workhome' %}"><i class="fa fa-users" style="font-size: 40px;"></i><p style="font-size: small;">Workspace</p></a>
		<a href="{% url 'inbox' %}"><i class="fa fa-envelope" style="font-size: 40px;"></i><p style="font-size: small;">Mail</p></a>
		<a href="{% url 'calendarapp:calendar' %}"><i class="fa fa-calendar" style="font-size: 40px;"></i><p style="font-size: small;">Calendar</p></a>
		<a class="active" href="{% url 'todo:todo' %}"><i class="fas fa-tasks" style="font-size: 40px;"></i><p style="font-size: small;">To-do</p></a>
		<a href="{% url 'chat' request.user %}"><i class="fas fa-comment-dots" style="font-size: 40px;"></i><p style="font-size: small;">Chat</p></a>
		<a href="{% url 'logout' %}"><i class="fa fa-sign-out" style="font-size: 40px;"></i><p style="font-size: small;">Logout</p></a>
	</div>
  <h1 class="title">{% block title %}{% endblock %}</h1>
  <hr>

  {% block content %}
  {% endblock %}

  {% block script %}
  {% endblock %}
</body>
</html>

templates/todo/list.html
{% extends 'todo/base.html' %}

{% block title %}
To-Do List
{% endblock %}

{% block content %}
<div class="content">
    <form action="/todo/" method = "POST">
        {% csrf_token %}
        {{form.title}}
        <input class="btn btn-info right" type="submit" value="Add Item">
    </form>
    
    <ul>
        {% for task in all_items %}
            <li>
            {% if task.complete == True %}
            <strike>{{task}}</strike>
            {% else %}
            <span>{{task}}</span>
            {% endif %}
            <a class="btn btn-sm btn-danger" href="{% url 'todo:delete_task' task.id %}">Delete</a>
            <a class="btn btn-sm btn-info" href="{% url 'todo:update_task' task.id %}">Update</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/todo/update_task.html
{% extends 'todo/base.html' %}

{% block title %}
Update Task
{% endblock %}

{% block content %}

    <form action="/todo/" method = "POST">
        {% csrf_token %}
        <table class="form form-table">
        {{form}}
        </table>
        <input class="btn btn-info" type="submit" value="Update Task">
    </form>

{% endblock %}